### ISSUE TITLE
Replace usage of Site URL with relative URLs

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-giphy#20]
#### Summary

When `/giphy (search)` is run and there is no `Site URL` set in the server settings, the request has a nil pointer exception, and responds back with
> Command with a trigger of '/giphy' not found. Click here to send as a message.

The server should instead use relative URLs so there is no error.

**Comment by hanzei** [comment]
Since https://github.com/mattermost/mattermost-server/pull/11477 I don't think we need the SiteURL any longer. We can just use relative URLs. 

@mickmister What do you think about redefining the purpose of the ticket and going with relative URLs?

**Comment by mickmister** [comment]
@hanzei Great, updated the ticket :+1:
