### ISSUE TITLE
Reduce button for gifs from plugin

### ISSUE THREAD

**Issue by florck** [mattermost/mattermost-plugin-giphy#5]
This is a feature request !
My team mates would love to have the opportunity to reduce the gif posted like any other image with the small button : 
open:
![image](https://user-images.githubusercontent.com/9990348/58237922-85f32d00-7d46-11e9-8ce7-e0e7d9038c8a.png)
closed:
![image](https://user-images.githubusercontent.com/9990348/58237954-95727600-7d46-11e9-8000-ee7e27789360.png)

I don't know if this is feasable indeed.

Thank you a lot.

Out of subject Post Scriptum:
Very nice job. I'm maybe one of the early adopters since mattermost 5.10 just arrived with ephemeral messages, and it already works like a charm !

**Comment by levb** [comment]
Hi, this was an experimental implementation. It relies on "slack attachments" in Mattermost, and I do not think these can be compacted.

Arguably, a (much) better implementation could be done with a custom post type and rendering, but (a) this would be substantial extra work, and (b) I am not sure if custom post types are currently supported for ephemeral messages, need to check.

I am going to label this request as a "Help Wanted", @florck any interest in working on this improvement?

**Comment by levb** [comment]
This requires changes from Mattermost either way - I do not believe that ephemeral messages can use custom post types, nor can the plugin control the appearance of embedded images in slack attachments.

**Comment by mickmister** [comment]
@levb We can post a link to the gif in a post instead of a slack attachment, and Mattermost will render it with the minimize option.

**Comment by mickmister** [comment]
> I do not believe that ephemeral messages can use custom post types, nor can the plugin control the appearance of embedded images in slack attachments.

@levb To be clear, the post that we want to minimize is the public post, not the ephemeral one. I think this can be implemented as described in my previous comment.

**Comment by hanzei** [comment]
FYI: MM supports custom post types for ephemeral messanges with `registerPostTypeComponent(type, component)`

**Comment by hanzei** [comment]
Closing as the plugin is not longer maintained.
