### ISSUE TITLE
Make "weirdness" configurable

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-giphy#8]
It is currently hardcoded, should be added as a configurable parameter, akin to "Rating"

**Comment by dnguy078** [comment]
https://github.com/mattermost/mattermost-plugin-giphy/pull/18

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-plugin-giphy/pull/18

Thanks @dnguy078 for the contribution
